### PR TITLE
disable `RSpec/ExampleLength` and `RSpec/NamedSubject`

### LINKED ISSUE #68: Disable RSpec/NamedSubject
https://docs.rubocop.org/rubocop-rspec/cops_rspec.html#rspecnamedsubject

for `RSpec/NamedSubject`,a good example from the official documentation is as follows:

```Ruby
# good
RSpec.describe Foo do
  subject(:user) { described_class.new }

  it 'is valid' do
    expect(user.valid?).to be(true)
  end
end
```

So I think NamedSubject is basically used in the model class specs.
However, NamedSubject applies to controller specs and request specs. I would like to remove it because it names the subject with a name that is not a class name, which does not make sense at first glance when reading it.

```Ruby
subject (:request_to_api) { get '/api/users' }

it 'returns 200' do
  request_to_api # <- what is it?
  expect(response).to have_http_status(200)
end
```

### LINKED ISSUE #69: Change RSpec/ExampleLength MAX value from 5 -> 7
https://docs.rubocop.org/rubocop-rspec/cops_rspec.html#rspecexamplelength
It feels too short.
Short EXAMPLES are easy to look at, but often do not cover the large number of DB settings.
and It is not possible to define many `let` because of `RSpec/MultipleMemoizedHelpers`.
However, in my opinion, I would rather have more lines of example than more `let`, because I think there is less information to look at when the example fails.

### PR DESCRIPTION
**Pull request by tana2034**
closes #68, closes #69

### CODE REVIEW

**Comment by yykamei** [comment]
Link this PR to the associated issues!

https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

**Comment by tana2034** [comment]
Thanks for your advice, I fix them

**Comment by yykamei** [comment]
Multiple issues 🙏 

Screen Shot 2022-03-23 at 14 55 00

**Review by yykamei — APPROVED** [review]
:shipit:

**Pull request merged**
